### ISSUE TITLE
Does not install on 32bit raspberry pi, onnxruntime cannot be installed.

### ISSUE THREAD

**Issue by Ramblurr** [MycroftAI/mimic3#29]
**Describe the bug**

`mycroft-pip install mycroft-plugin-tts-mimic3[all]` fails to install  on a raspberry pi 3 or 4 running 32 bit raspbian.

```
ERROR: Could not find a version that satisfies the requirement onnxruntime
ERROR: No matching distribution found for onnxruntime
```

It seems pypi has no pre-built onnxruntime for 32bit ARM. Browsing around the onnx site, it seems it is not supported.

**To Reproduce**
1. Install 32bit raspbian
2. `mycroft-pip install mycroft-plugin-tts-mimic3[all]` 

**Expected behavior**
[The documentation](https://mycroft-ai.gitbook.io/docs/mycroft-technologies/mimic-tts/mimic-3) says it should work on 32bit armv7l.

**Environment (please complete the following information):**
 - Device type: RPI 3 B and RPI 4
 - OS: raspbian bullseye
 - Mycroft-core version: latest master

**Comment by synesthesiam** [comment]
`mycroft-pip install -f https://synesthesiam.github.io/prebuilt-apps/ mycroft-plugin-tts-mimic3[all]`

**Comment by Ramblurr** [comment]
@synesthesiam ... your solution references your own repo? Shouldn't this be fixed here in the official repo?

**Comment by synesthesiam** [comment]
Probably, but I don't work for Mycroft anymore so this is the solution for now :man_shrugging:
