### ISSUE TITLE
Clarify and supply access to project logo artwork

### ISSUE THREAD

**Issue by nomandera** [MycroftAI/mimic3#48]
**Is your feature request related to a problem? Please describe.**

It is not clear which logo relates to the mimic3 project. Several options exist in the various websites and artwork.

**Describe the solution you'd like**

Supply access to high quality logo artwork (vector/svg) and ideally a series of transparent png at the typical resolutions

**Describe alternatives you've considered*

I can guess at and extract what I believe is the logo from one of the images hosted [here](https://github.com/MycroftAI/mimic3/tree/master/img)

**Additional context**

When self hosting mimic3 it is useful to have access to the logo for projects such as:

- https://github.com/walkxcode/dashboard-icons
- https://github.com/benphelps/homepage

**Comment by synesthesiam** [comment]
This SVG is the Mimic logo: https://github.com/MycroftAI/mimic3/blob/master/img/Mimic_color.svg
